build:
  stage: build
  tags:
    - ipanema
  script: 
    - curl http://bossa.gforge.inria.fr/linux-config > .config
    - make oldconfig
    - make -j48

checkpatch-ipanema:
  stage: build
  tags:
    - ipanema
  script:
    - ./scripts/checkpatch.pl -f kernel/sched/*.c kernel/sched/*.h include/linux/ipanema*.h
  allow_failure: true
