stages:
  - build
  - build-ipanema

build-kernel:
  stage: build
  tags:
    - ipanema
  script:
    - make defconfig
    - make localmodconfig
    - make ipanema.config
    - make -j48
  cache:
    untracked: true
    key: modules-cache
    paths:
      - .config
      - Module.symvers

build-kernel-sched-monitor:
  stage: build
  tags:
    - ipanema
  script:
    - make defconfig
    - make localmodconfig
    - make ipanema.config
    - make sched_monitor.config
    - make -j48

build-ipanema-policies:
  stage: build-ipanema
  tags:
    - ipanema
  script:
    - make prepare
    - make modules_prepare
    - cd ipanema/modules && make -j48 && cd ../..
  cache:
    untracked: true
    key: modules-cache
    paths:
      - .config
      - Module.symvers

build-ipanema-ipastart:
  stage: build-ipanema
  tags:
    - ipanema
  script:
    - cd tools/ipanema/ipastart && make && cd ../../..


build-ipanema-ipasetspolicy:
  stage: build-ipanema
  tags:
    - ipanema
  script:
    - cd tools/ipanema/ipasetpolicy && make && cd ../../..
