stages:
  - build
  - build-ipanema

build-kernel:
  stage: build
  tags:
    - ipanema
  script:
    - make defconfig
    - make localmodconfig
    - make ipanema.config
    - make -j48
  cache:
    key: kbuild-cache
    paths:
      - Module.symvers
      - System.map
      - .config
      - include/generated

build-ipanema-policies:
  stage: build-ipanema
  tags:
    - ipanema
  script:
    - cd ipanema/modules && make -j48 && cd ../..
  cache:
    key: kbuild-cache
    paths:
      - Module.symvers
      - System.map
      - .config
      - include/generated

build-ipanema-ipastart:
  stage: build-ipanema
  tags:
    - ipanema
  script:
    - cd tools/ipanema/ipastart && make && cd ../../..


build-ipanema-ipasetspolicy:
  stage: build-ipanema
  tags:
    - ipanema
  script:
    - cd tools/ipanema/ipasetpolicy && make && cd ../../..
